# Generated by Django 5.2.8 on 2026-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_diaria_horas', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Configuração',
            },
        ),
        migrations.CreateModel(
            name='EntradaBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
