# Generated by Django 5.2.8 on 2026-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_horas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entradabancohoras',
            index=models.Index(fields=['tipo'], name='banco_horas_tipo_142473_idx'),
        ),
        migrations.AddIndex(
            model_name='entradabancohoras',
            index=models.Index(fields=['data'], name='banco_horas_data_276eeb_idx'),
        ),
    ]
