# Generated by Django 5.2.8 on 2026-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('suporte', 'Suporte'), ('tecnico', 'Técnico'), ('rotina', 'Rotina')], max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
