# Generated by Django 5.2.8 on 2026-05-26 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['-data', '-criada_em']},
        ),
        migrations.AddField(
            model_name='demanda',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
