# Generated by Django 5.2.8 on 2026-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_pessoa_setor_demanda_responsavel_pessoa_setor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['status'], name='demandas_de_status_25dba6_idx'),
        ),
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['data'], name='demandas_de_data_1b933b_idx'),
        ),
        migrations.AddIndex(
            model_name='demanda',
            index=models.Index(fields=['categoria'], name='demandas_de_categor_be7104_idx'),
        ),
    ]
